
[tool.poetry]
name = "omega"
version = "0.7.0"
description = "分布式高速行情服务器"
authors = ["jieyu <code@jieyu.ai>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
aiocache = "^0.11.1"
aiohttp = "^3.7.3"
aioredis = "^1.3.1"
APScheduler = "^3.6.3"
arrow = "0.15.5"
asyncpg = "^0.21.0"
cfg4py = "^0.8.0"
fire = "^0.3.1"
gino = "^1.0.1"
hiredis = "^1.1.0"
numba = "0.49.1"
psutil = "^5.7.3"
pytz = "^2020.4"
"ruamel.yaml" = "^0.16.0"
sanic = "^20.9.1"
sh = "^1.14.1"
termcolor = "^1.1.0"
xxhash = "^2.0.0"
zillionare-omicron = "0.3.0"
numpy = "1.19.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
omega = 'omega.cli:main'

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests/.*/setup.py
)/
'''

[tool.isort]
# black compatible settings, see https://github.com/psf/black/blob/master/docs/compatible_configs
line_length = 88
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true
